### ISSUE TITLE
handling multiple email received?

### ISSUE THREAD

**Issue by derit** [SebastiaanKlippert/lambda-ses-forwarder#1]
how to handling multiple email received?
for example
received1@test.com
received2@test.com
received3@test.com

**Comment by SebastiaanKlippert** [comment]
Do you mean that if you have setup a catch-all rule on your domain the mail will be forwarded in a loop?
Possibly, yes, good point, thanks.

I will see if I can fix that.

**Comment by SebastiaanKlippert** [comment]
That is probably not what you mean, but it made me find the bug that I did not skip `Cc` headers.

Do you mean that it gets forwarded only once in the case you describe? It looks like SES only sends one Lambda event, which is exactly what I want for my use case. I only want to see the mail once.
I think it is correct behaviour for a catch-all address or you would get thesee loops, if you create a ruleset for each recepient it will also get delivered multiple times.

**Comment by derit** [comment]
i solve with @domain.com in rule set from aws, all email coming now can received, but i have a problem when replying incoming email
