### ISSUE TITLE
Domain contains illegal character

### ISSUE THREAD

**Issue by ioannist** [SebastiaanKlippert/lambda-ses-forwarder#2]
If you use an email or "name <email>" in FORWARD_FROM env, an extra %! gets appended in From and you get an error.

```
From: "EXTRA string=some name" <fromname@gmail.com%!>
To: <toname@gmail.com>
SES SendRawEmail failed: InvalidParameterValue: Domain contains illegal character status code: 400, request id: 7e501eb2-3dce-4fbb-a862-c0754a0385dc: errorString null
```

If you use "%s <fromname@gmail.com>" as the env, it works fine

**Comment by SebastiaanKlippert** [comment]
Yeah I see. Don't know why I said it's optional, but I will fix it today and make the %s optional.

Thanks for the report.
